package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,

	LEAVE_NODE,

	TOKEN, TOKEN_REQUEST,

	PING, PONG, PING_SUSPECT, CONFIRMED_SUSPECT,
	NODE_FAILED, NODE_RECOVERED,

	HAVE_TOKEN, HAVE_TOKEN_RESPONSE,
}
